configName: DSP_TU2
folderName: DSP_TU2
format_version: v1.0
frameworkPath: ..\..\..\..\Harmony3
processor: PIC32MZ0512EFE064
projectName: DSP_TU2
settings:
  PackageFilter: bootloader;bootloader_apps_i2c;bootloader_apps_uart;bootloader_apps_usb;bsp;CEC173x_soteria_lib;classb_pic32cm_mc;classb_pic32mzw1_wfi32e01;classb_sam_e5x_d5x;classb_sam_e70_s70_v70_v71;core;core_apps_pic32cm_jh00_jh01;core_apps_pic32cm_le_ls;core_apps_pic32cxbz2_wbz45;core_apps_pic32mz_w1;core_apps_sam_9x60;core_apps_sam_a5d2;core_apps_sam_c20_c21;core_apps_sam_d21_da1;core_apps_sam_d5x_e5x;core_apps_sam_rh707;crypto;crypto_apps_large_hash;csp;csp_apps_cec173x;csp_apps_pic32cm_jh00_jh01;csp_apps_pic32cm_mc00;csp_apps_pic32cxbz2_wbz45;csp_apps_pic32mk;csp_apps_pic32mz_da;csp_apps_pic32mz_w1;csp_apps_sam_a5d2;csp_apps_sam_c20_c21;csp_apps_sam_d10;csp_apps_sam_d11;csp_apps_sam_d21_da1;csp_apps_sam_d5x_e5x;csp_apps_sam_g55;csp_apps_sam_l10_l11;csp_apps_sam_l21;csp_apps_sam_l22;csp_apps_sam_rh707;dev_packs;ethercat;gfx;gfx_apps_pic32mz_da;gfx_apps_pic32mz_ef;gfx_apps_sam_9x60;gfx_apps_sam_a5d2;gfx_apps_sam_c20_c21;gfx_apps_sam_l22;harmony-services;mbed_os_rtos;mc_apps_pic32cm_mc;mc_apps_pic32mk;mc_apps_sam_rh71;micrium_ucos3;net_10base_t1s;net_apps_sam_e5x;net_apps_sam_e70_v71;net_apps_sam_rh71;quick_docs;smartenergy;smartenergy_g3_apps;smartenergy_prime_apps;touch;touch_apps;touch_host_driver;usb;usb_apps_dual_role;wireless_system_pic32mzw1_wfi32e01;wireless_wifi;x2c
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.58\atdf\PIC32MZ0512EFE064.atdf
